name: ci

on:
  push:
    branches: ["*"]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.1'
      - name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.1'

      - name: Unit Test
        run: go test ./internal/... ./pkg/...

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.1'

      - name: Integration tests
        run: "docker-compose up \
          --build \
          --abort-on-container-exit \
          --exit-code-from integration-test \
          integration-test"